// Entity mappings for BambuLab (ha-bambulab) — German
// When Home Assistant is set to German, the BambuLab integration uses translated entity names.
export default {
  sensor: [
    ["status", ["druckstatus", "aktuelle_arbeitsschritt", "current_print_state"]],
    ["printer_state", ["druckstatus", "printer_state"]],
    ["progress", ["druckfortschritt", "progress"]],
    ["duration", ["druckdauer", "print_duration"]],
    ["eta", ["verbleibende_zeit", "print_time_left", "print_eta"]],
    ["filename", ["gcode_dateiname", "name_der_aufgabe", "filename"]],
    ["current_layer", ["aktuelle_schicht", "current_layer"]],
    ["total_layers", ["gesamtzahl_der_schichten", "total_layer", "total_layers"]],
    ["filament_used", ["drucklaenge", "aktiver_slot", "filament_used"]],
    ["current_print_message", ["current_print_message"]],
    ["current_display_message", ["current_display_message"]],
    ["hotend", ["temperatur_der_duese", "temperatur_der_duese_0", "temperatur_der_duse", "extruder_temperature", "extruder_temp"]],
    ["bed", ["druckbetttemperatur", "bed_temperature", "bed_temp"]],
    ["position_x", ["toolhead_position_x"]],
    ["position_y", ["toolhead_position_y"]],
    ["position_z", ["toolhead_position_z"]],
    ["object_height", ["object_height"]]
  ],
  number: [
    ["hotend_target", ["zieltemperatur_der_duese", "zieltemperatur_der_duese_0", "zieltemperatur_der_duse", "extruder_target"]],
    ["bed_target", ["zieltemperatur_des_druckbett", "zieltemperatur_vom_druckbett", "bed_target"]],
    ["chamber_target", ["heater_chamber_target"]],
    ["speed_factor", ["geschwindigkeitsprofil", "speed_factor"]],
    ["flow_factor", ["flow_factor"]]
  ],
  button: [
    ["cancel", ["abbrechen", "cancel_print"]],
    ["pause", ["pause", "pause_print"]],
    ["resume", ["fortsetzen", "resume_print"]],
    ["emergency", ["emergency_stop"]],
    ["home_all", ["home_all_axes"]],
    ["home_x", ["home_x_axis"]],
    ["home_y", ["home_y_axis"]],
    ["home_z", ["home_z_axis"]],
    ["fw_restart", ["firmware_restart"]],
    ["host_restart", ["host_restart"]],
    ["server_restart", ["server_restart"]],
    ["host_shutdown", ["host_shutdown"]],
    ["klipper_restart", ["restart_klipper"]]
  ],
  camera: [["thumbnail", ["thumbnail", "titelbild"]]],
  ui: {
    eta: "ETA",
    elapsed: "Verstrichen",
    file: "Datei",
    progress: "Fortschritt",
    hotend: "Hotend",
    bed: "Bett",
    speed: "Geschwindigkeit",
    flow: "Fluss",
    pause: "Pause",
    resume: "Fortsetzen",
    cancel: "Abbrechen",
    macros: "Makros",
    move: "Bewegen",
    misc: "Sonstiges",
    more: "Mehr",
    movement: "Bewegung",
    system: "System",
    temperatures: "Temperaturen",
    fans_outputs: "Lüfter & Ausgänge",
    klipper_control: "Klipper-Steuerung",
    service_control: "Dienst-Steuerung",
    host_control: "Host-Steuerung",
    restart_klipper: "Klipper neu starten",
    firmware_restart: "Firmware neu starten",
    server_restart: "Server neu starten",
    host_restart: "Host neu starten",
    host_shutdown: "Host herunterfahren",
    reboot_host: "Host neu starten",
    shutdown_host: "Host herunterfahren",
    cameras: "Kameras",
    camera_fallback: "Kamera",
    home_all: "Alle"
  }
};
