// Entity mappings for Moonraker/Klipper — English
export default {
  sensor: [
    ["status", ["current_print_state"]],
    ["printer_state", ["printer_state"]],
    ["progress", ["progress"]],
    ["duration", ["print_duration"]],
    ["eta", ["print_time_left", "print_eta"]],
    ["filename", ["filename"]],
    ["current_layer", ["current_layer"]],
    ["total_layers", ["total_layer", "total_layers"]],
    ["filament_used", ["filament_used"]],
    ["current_print_message", ["current_print_message"]],
    ["current_display_message", ["current_display_message"]],
    ["hotend", ["extruder_temperature", "extruder_temp"]],
    ["bed", ["bed_temperature", "bed_temp"]],
    ["position_x", ["toolhead_position_x"]],
    ["position_y", ["toolhead_position_y"]],
    ["position_z", ["toolhead_position_z"]],
    ["object_height", ["object_height"]]
  ],
  number: [
    ["hotend_target", ["extruder_target"]],
    ["bed_target", ["bed_target"]],
    ["chamber_target", ["heater_chamber_target"]],
    ["speed_factor", ["speed_factor"]],
    ["flow_factor", ["flow_factor"]]
  ],
  button: [
    ["cancel", ["cancel_print"]],
    ["pause", ["pause_print"]],
    ["resume", ["resume_print"]],
    ["emergency", ["emergency_stop"]],
    ["home_all", ["home_all_axes"]],
    ["home_x", ["home_x_axis"]],
    ["home_y", ["home_y_axis"]],
    ["home_z", ["home_z_axis"]],
    ["fw_restart", ["firmware_restart"]],
    ["host_restart", ["host_restart"]],
    ["server_restart", ["server_restart"]],
    ["host_shutdown", ["host_shutdown"]],
    ["klipper_restart", ["restart_klipper"]]
  ],
  camera: [["thumbnail", ["thumbnail"]]],
  ui: {
    eta: "ETA",
    elapsed: "Elapsed",
    file: "File",
    progress: "Progress",
    hotend: "Hotend",
    bed: "Bed",
    speed: "Speed",
    flow: "Flow",
    pause: "Pause",
    resume: "Resume",
    cancel: "Cancel",
    macros: "Macros",
    move: "Move",
    misc: "Misc",
    more: "More",
    movement: "Movement",
    system: "System",
    temperatures: "Temperatures",
    fans_outputs: "Fans & Outputs",
    klipper_control: "Klipper Control",
    service_control: "Service Control",
    host_control: "Host Control",
    restart_klipper: "Restart Klipper",
    firmware_restart: "Firmware Restart",
    server_restart: "Server Restart",
    host_restart: "Host Restart",
    host_shutdown: "Host Shutdown",
    reboot_host: "Reboot Host",
    shutdown_host: "Shutdown Host",
    cameras: "Cameras",
    camera_fallback: "Camera",
    home_all: "All"
  }
};
